# Generated by Django 2.1.5 on 2019-02-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_price',
            new_name='price_sum',
        ),
    ]
